#include <stdio.h>

long e1();
long e12();
long e14();
void e16();

void main() {
	//printf("sum %d\n",  e1());
	//printf("num %d\n", e12());
	// *** printf("num %d\n", e13()); ***
}

void e16() {
	/*
	2^15 = 32768 and the sum of its digits is 3 + 2 + 7 + 6 + 8 = 26.
	What is the sum of the digits of the number 2^1000?
	*
	long long num = 2;
	for (int i = 1; i <= 1000; i++) {
		num = num * 2;
		printf("%d, ", num);
	}
	//char str[32];
	//sprintf(str, "%d", num);
	//printf("%d", num);
	//return str;
	*/
}

long e14() {
	/*
	The following iterative sequence is defined for the set of positive integers:

	n → n/2 (n is even)
	n → 3n + 1 (n is odd)

	Using the rule above and starting with 13, we generate the following sequence:

	13 → 40 → 20 → 10 → 5 → 16 → 8 → 4 → 2 → 1
	It can be seen that this sequence (starting at 13 and finishing at 1) 
	contains 10 terms. Although it has not been proved yet (Collatz Problem), 
	it is thought that all starting numbers finish at 1.

	Which starting number, under one million, produces the longest chain?
	*/
	long num = 0;
	long ctr = 0;
	long high_ctr = 0;
	long high_num = 0;
	for (int i = 13; i < 1000000; i++) {
		ctr = 0;
		num = i;
		while (num != 1) {
			if (num % 2 == 0) {
				num = num / 2;
				ctr++;
			}
			else {
				num = 3 * num + 1;
				ctr++;
			}
			//printf("num: %d", num);
			if (ctr > high_ctr) {
				high_num = i;
				high_ctr = ctr;
				//printf("num: %d, ctr: %d", num, ctr);
			}
		}
	}
	return high_num;
}

long e12() {
	/*
	The sequence of triangle numbers is generated by adding the natural numbers. 
	So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

	1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

	Let us list the factors of the first seven triangle numbers:

	 1: 1
	 3: 1,3
	 6: 1,2,3,6
	10: 1,2,5,10
	15: 1,3,5,15
	21: 1,3,7,21
	28: 1,2,4,7,14,28
	We can see that 28 is the first triangle number to have over five divisors.

	What is the value of the first triangle number to have over five hundred divisors?
	*/
	long i = 1;
	long num = 0;
	long ctr = 0;
	long maxCtr = 0;
	for(;;) {
		ctr = 0;
		num += i;
		//printf("num: %d, ", num);
		for (long j = 1; j <= num; j++) {
			if (num % j == 0) {
				//printf("%d ,", num);
				ctr++;
				if (ctr > 500) {
					return(num);
					break;
				}
			}
		}
		if (ctr > maxCtr) {
			maxCtr = ctr;
			printf("ctr; %d\n", ctr);
		}
		i++;
	}
}

long e1() {
	/*If we list all the natural numbers below 10 that are multiples of 3 or 5, 
	 *we get 3, 5, 6 and 9. The sum of these multiples is 23.
	 *Find the sum of all the multiples of 3 or 5 below 1000.
	 */
	int i;
	int sum;
	sum = 0;
	for (i = 0; i < 1000; i++) {
		if (i % 3 == 0 || i % 5 == 0) {
			sum += i;
		}
	}
	return sum;
}